services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        restart: always
        env_file:
            - bot/.env
        volumes:
            - .:/bot

    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        restart: always
        volumes:
            - .:/api
        ports:
            - "8000:8000"
